//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareTravelPackage
    {
        public int STP_Id { get; set; }
        public string PackageName { get; set; }
        public string Memo { get; set; }
        public System.DateTime TravelDateTime { get; set; }
        public string Places { get; set; }
    }
}
