//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllFeedingRoom
    {
        public int cp_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public string opentime { get; set; }
        public string note { get; set; }
        public double lat { get; set; }
        public double lng { get; set; }
        public Nullable<double> distance { get; set; }
    }
}
