//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWBCityRegionLocation
    {
        public int CRL_Id { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public double RLat { get; set; }
        public double RLng { get; set; }
    }
}
