//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareTravelPlace
    {
        public int STP_Id { get; set; }
        public string Place_Id { get; set; }
        public string PlaceName { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public double Rating { get; set; }
        public double Lat { get; set; }
        public double Lng { get; set; }
        public string PType { get; set; }
    }
}
